# Generated by Django 4.1 on 2022-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_sellerregistration_tb_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistration_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
