# Generated by Django 4.1 on 2022-09-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_addcategory_tb'),
        ('seller', '0004_sellerregistration_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.addcategory_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregistration_tb')),
            ],
        ),
    ]
