# Generated by Django 4.1 on 2022-09-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_buyerorder_tb_status'),
        ('seller', '0005_addproduct_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackorder_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerorder_tb')),
            ],
        ),
    ]
