# Generated by Django 4.1 on 2022-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregistration_tb',
            name='country',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
