# Generated by Django 4.1 on 2022-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_addtocart_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart_tb',
            name='totalprice',
            field=models.IntegerField(default=1),
        ),
    ]
