# Generated by Django 4.1 on 2022-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_addtocart_tb_file_alter_addtocart_tb_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart_tb',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
