# Generated by Django 4.1 on 2022-09-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_alter_addtocart_tb_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart_tb',
            name='file',
        ),
    ]
