# Generated by Django 4.1 on 2022-09-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_addproduct_tb'),
        ('buyer', '0007_remove_addtocart_tb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyerorder_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=20)),
                ('contactnumber', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerregistration_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.addproduct_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregistration_tb')),
            ],
        ),
    ]
