# Generated by Django 4.1 on 2022-09-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_buyerorder_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
